name: Zip

on:
  workflow_dispatch:
  push:
    tags: "v*.*.*"

env:
  prefix: unipack_resource

jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Archive
        run: |
          mkdir dist
          zip -r dist/${prefix}_${GITHUB_REF_NAME}.zip . -x ".*/*" "dist/*" ".gitignore"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/*
